### ISSUE TITLE
Softkeyboard does not hide when unfocussing, neither does next button get pressed when using softkeyboard return

### ISSUE THREAD

**Issue by KsgFellow** [ResearchStack/ResearchStack#496]
Hello,
I noticed that the Softkeyboard does not behave as expected when answering text / numeric questions.

I'd expect the softkeyboard to either hide/close on pressing return or to bring me to the next step.
Furthermore the softkeyboard appears again after closing it and clicking the next button in the submit bar. (Which is certainly not expected behaviour?).

Any advice on this?

**Comment by dukemike** [comment]
While not a solution, I was able to get around having the user close the keyboard to view the next button my having the next step be an instruction step. If I recall, this occurs when there are multiple text input steps in a row.


On Feb 18, 2019, at 10:09 AM, KsgPhellow <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I noticed that the Softkeyboard does not behave as expected when answering text / numeric questions.

I'd expect the softkeyboard to either hide/close on pressing return or to bring me to the next step.
Furthermore the softkeyboard appears again after closing it and clicking the next button in the submit bar. (Which is certainly not expected behaviour?).

Any advice on this?

**Comment by KsgFellow** [comment]
Hm the problem of the Softkeyboard coming up again happens actually when the next step is an instruction or summary step. 

But yes, that's not a solution thats feasable for me.

As before, any advice would be greatly appreciated.

**Comment by KsgFellow** [comment]
>If I recall, this occurs when there are multiple text input steps in a row.

As far as I can tell that is correct, the Step where this problem occurs has 2 integer input fields.

Can anyone give advice on this?

**Comment by KsgFellow** [comment]
I was able to fix this (atleast it seems that way at the moment) by implementing a dispatchTouchEvent in my ViewTaskActivity override.

`
@Override
    public boolean dispatchTouchEvent(MotionEvent event) {
        if (event.getAction() == MotionEvent.ACTION_DOWN) {
            View v = getCurrentFocus();
            if ( v instanceof EditText) {
                Rect outRect = new Rect();
                v.getGlobalVisibleRect(outRect);
                if (!outRect.contains((int)event.getRawX(), (int)event.getRawY())) {
                    v.clearFocus();
                    InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
                    imm.hideSoftInputFromWindow(v.getWindowToken(), 0);
                }
            }
        }
        return super.dispatchTouchEvent( event );
    }
`
